package com.example.core.datetime

const val BIRTHDAY_PATTERN_FR = "^(0[1-9]|1\\d|2\\d|3[01])/(0[1-9]|1[0-2])/(19|20)\\d{2}$"
const val BIRTHDAY_PATTERN_US = "^(19|20)\\d{2}/(0[1-9]|1[0-2])/(0[1-9]|1\\d|2\\d|3[01])$"
const val TIME_RESPONSE_PATTERN = "HH:mm:ss"
const val DATE_RESPONSE_PATTERN = "yyyy-MM-dd'T'HH:mm:ssZ"
const val DATE_WITH_MILLIS_RESPONSE_PATTERN = "yyyy-MM-dd'T'HH:mm:ssZ"
const val DATE_PATTERN_NO_PUNCTUATION = "yyyy_MM_dd_HH_mm_ss"
const val DATE_PATTERN_EMD = "EEE MM/dd"
const val DATE_PATTERN_EDM = "EEE dd/MM"
const val DATE_PATTERN_EDMY_DOT = "EEE. dd/MM/YY"
const val DATE_PATTERN_EMDY_DOT = "EEE. MM/dd/YY"
const val DATE_PATTERN_EDMY = "EEE dd/MM/YY"
const val DATE_PATTERN_EMDY = "EEE MM/dd/YY"
const val DATE_PATTERN_SLASH_DMY = "dd/MM/yyyy"
const val DATE_PATTERN_SLASH_YMD = "yyyy/MM/dd"
const val DATE_PATTERN_DMY = "dd MMMM yyyy"
const val DATE_PATTERN_MDY = "MMMM dd yyyy"
const val DATE_PATTERN_FOR_REQUEST = "yyyy-MM-dd"
const val TIME_PATTERN_SLASH = "HH/mm"
const val TIME_PATTERN_SEMICOLON = "HH:mm"
const val DATE_PATTERN_MY = "MMMM yyyy"
const val DATE_PATTERN_DM = "dd/MM"
const val DATE_PATTERN_MD = "MM/dd"
const val TIME_PATTERN_FFMPEG_FILE_TIMESTAMP = "HH:mm:ss.SSS"
